---
apiVersion: v1
kind: ConfigMap
data:
  extraconfigs.yaml: |
    http:
      ip_ban_enabled: true
      login_attempts_threshold: 5
      trusted_proxies:
      - 10.244.0.0/16
      use_x_forwarded_for: true
metadata:
  labels:
    findme: yea
  name: config-files
---
apiVersion: v1
kind: ConfigMap
data:
  fix_config.sh: |-
    #!/bin/bash
    filename="/config/configuration.yaml"
    lines_to_add_file="/hass/lines_to_add.txt"
    # Check if the configuration.yaml file exists keep running. else exit clean
    if [ ! -f "$filename" ]; then
        echo "Check if the configuration.yaml file exists"
        echo "File not found: $filename"
        exit 0
    fi
    # Check if filename and lines_to_add_file are provided
    if [ -z "$filename" ] || [ -z "$lines_to_add_file" ]; then
        echo "Usage: $0 <filename> <lines_to_add_file>"
        exit 1
    fi

    # Check if the lines to add file exists
    if [ ! -f "$lines_to_add_file" ]; then
        echo "Lines to add file not found: $lines_to_add_file"
        exit 1
    fi

    # Read lines from the file into an array
    IFS=$'\n' read -d '' -r -a lines_to_add < "$lines_to_add_file"

    # Loop through each line to add
    for line_to_add in "${lines_to_add[@]}"; do
        # Check if the line is already present
        if grep -qF "$line_to_add" "$filename"; then
            echo "'$line_to_add' already exists in $filename"
        else
            # Append the line to the file
            echo "$line_to_add" >> "$filename"
            echo "Added '$line_to_add' to $filename"
        fi
    done
  lines_to_add.txt: |-
    homeassistant:
      packages: !include_dir_named packages
metadata:
  labels:
    app.kubernetes.io/instance: home-assistant
    app.kubernetes.io/name: home-assistant
  name: home-assistant-config-init