apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: home-assistant-role
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: home-assistant-rolebind
roleRef:
  kind: ClusterRole
  name: home-assistant-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: default
    namespace: home-assistant